import Head from "next/head";
import Script from "next/script";
import Inputs from "../components/Inputs";
import SearchBar from "../components/SearchBar";
import Table from "../components/Table";
import axios from 'axios';


export default function Home({data} : {data : object[] | string}) {

  console.log(data)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inputs />
      <SearchBar />
      <Table />
      
    </>
  );
}

// export async function getStaticProps()  {
  
  
//   try {
//     const {message} = await axios.get("http://localhost:3001/api/data");
//     return {
//       props: {
//         data: message
//       },
//       revalidate: 10
//     }
//   } catch(error) {
//     return {
//       props: {
//         data: stringify(error)
//       },
//       revalidate: 10
//     }
//   }

  
// }