import Head from "next/head";
import Script from "next/script";
import Inputs from "../components/Inputs";
import SearchBar from "../components/SearchBar";
import Table from "../components/Table";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inputs />
      <SearchBar />
      <Table />
    </>
  );
}
